name: Rotate GIF Sequentially

on:
  schedule:
    - cron: "*/1 * * * *"  # 테스트용: 1분마다 실행
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Rotate GIF sequentially
      run: |
        import os
        import shutil

        gif_dir = "gifs"
        index_file = "gif_index.txt"
        target_file = "anime-retro.gif"

        gifs = sorted([f for f in os.listdir(gif_dir) if f.endswith(".gif")])

        if not gifs:
            raise Exception("No GIFs found.")

        # read current index
        index = 0
        if os.path.exists(index_file):
            with open(index_file, "r") as f:
                index = int(f.read().strip())

        # bound check
        index = index % len(gifs)
        selected = gifs[index]

        # copy selected gif
        shutil.copyfile(os.path.join(gif_dir, selected), target_file)

        # update index
        next_index = (index + 1) % len(gifs)
        with open(index_file, "w") as f:
            f.write(str(next_index))

        print(f"Copied {selected} → {target_file}, next index = {next_index}")

      shell: python

    - name: Commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add anime-retro.gif gif_index.txt
        git commit -m "Update GIF sequentially" || echo "No changes"
        git push
