name: Rotate GIF

on:
  schedule:
    - cron: "*/1 * * * *"  # 1분마다 실행 (테스트용, 나중에 수정 권장)
  workflow_dispatch:       # 수동 실행도 가능

# 권한 설정 추가
permissions:
  contents: write

jobs:
  update-gif:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Rotate GIF
      run: |
        import os, random, shutil
        
        # gifs 디렉토리가 없으면 생성
        if not os.path.exists("gifs"):
            os.makedirs("gifs")
            print("Created gifs directory")
            exit(0)  # 첫 실행에서는 디렉토리만 만들고 종료
        
        gif_dir = "gifs"
        target_gif = "anime-retro.gif"
        
        # GIF 파일 목록 가져오기
        gifs = [f for f in os.listdir(gif_dir) if f.endswith(".gif")]
        
        # GIF 파일이 없으면 오류 메시지 출력
        if not gifs:
            print("Error: No GIF files found in gifs directory!")
            exit(1)
        
        # 랜덤으로 GIF 선택
        chosen = random.choice(gifs)
        
        # 선택된 GIF를 타겟 파일로 복사
        shutil.copyfile(os.path.join(gif_dir, chosen), target_gif)
        
        print(f"Successfully selected GIF: {chosen}")
      shell: python

    - name: Commit and push if changed
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add anime-retro.gif
        git commit -m "Update GIF: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push