name: Daily GIF Rotation at KST Midnight

on:
  schedule:
    - cron: "5 15 * * *"  # 한국 시간 00:05 (UTC+9 기준으로 15:05)
  workflow_dispatch:       # 수동 실행 옵션 유지

permissions:
  contents: write
  
jobs:
  rotate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Rotate GIF sequentially
      run: |
        import os
        import shutil
        import datetime
        from datetime import timezone, timedelta

        # 현재 시간을 한국 시간(KST)으로 기록
        kst = timezone(timedelta(hours=9))
        utc_time = datetime.datetime.now(timezone.utc)
        kst_time = utc_time.astimezone(kst)
        current_time = kst_time.strftime("%Y-%m-%d %H:%M:%S KST")
        print(f"Workflow running at: {current_time}")

        # 디렉토리 확인 및 생성
        gif_dir = "gifs"
        if not os.path.exists(gif_dir):
            print(f"Creating directory: {gif_dir}")
            os.makedirs(gif_dir)
            print("Please add GIF files to the 'gifs' directory")
            exit(0)

        index_file = "gif_index.txt"
        target_file = "anime-retro.gif"
        cache_version_file = "cache_version.txt"

        # GIF 파일 목록 가져오기
        gifs = sorted([f for f in os.listdir(gif_dir) if f.endswith(".gif")])
        print(f"Found {len(gifs)} GIF files: {gifs}")

        if not gifs:
            print("No GIFs found in the 'gifs' directory.")
            exit(0)

        # 현재 인덱스 읽기
        index = 0
        if os.path.exists(index_file):
            try:
                with open(index_file, "r") as f:
                    content = f.read().strip()
                    if content:
                        index = int(content.split('\n')[0])
            except Exception as e:
                print(f"Error reading index file: {e}")

        # 캐시 버스팅 버전 읽기
        cache_version = 1
        if os.path.exists(cache_version_file):
            try:
                with open(cache_version_file, "r") as f:
                    content = f.read().strip()
                    if content:
                        cache_version = int(content)
            except Exception as e:
                print(f"Error reading cache version file: {e}")

        # 유효성 검사
        index = index % len(gifs)
        selected = gifs[index]
        print(f"Selected GIF: {selected} (index {index})")

        # 타겟 파일이 존재하면 먼저 삭제 (변경 감지 보장)
        if os.path.exists(target_file):
            os.remove(target_file)
            
        # GIF 복사
        shutil.copyfile(os.path.join(gif_dir, selected), target_file)
        print(f"Copied {selected} to {target_file}")

        # 다음 인덱스 업데이트 (타임스탬프 포함)
        next_index = (index + 1) % len(gifs)
        with open(index_file, "w") as f:
            f.write(f"{next_index}\n# Last updated: {current_time}")
        
        # 캐시 버스팅 버전 업데이트
        new_cache_version = cache_version + 1
        with open(cache_version_file, "w") as f:
            f.write(str(new_cache_version))
        
        print(f"Updated index to {next_index}")
        print(f"Updated cache version to {new_cache_version}")
        print(f"Next GIF will be: {gifs[next_index]}")

        # README.md 파일이 존재하면 캐시 버스팅 파라미터 업데이트
        if os.path.exists("README.md"):
            try:
                with open("README.md", "r") as f:
                    readme_content = f.read()
                
                # 기존 캐시 버스팅 파라미터가 있는지 확인
                import re
                updated_content = re.sub(
                    r'(anime-retro\.gif\?cache-bust=)[0-9]+', 
                    f'\\1{new_cache_version}', 
                    readme_content
                )
                
                # 기존 파라미터가 없는 경우 anime-retro.gif를 찾아 파라미터 추가
                if updated_content == readme_content:
                    updated_content = re.sub(
                        r'(anime-retro\.gif)(?!\?)', 
                        f'\\1?cache-bust={new_cache_version}', 
                        readme_content
                    )
                
                with open("README.md", "w") as f:
                    f.write(updated_content)
                
                print("Updated README.md with new cache busting parameter")
            except Exception as e:
                print(f"Error updating README.md: {e}")
      shell: python

    - name: Commit and push
      run: |
        git config user.name "KyuHyeon Sung"
        git config user.email "dmp100@naver.com"
        git add -f anime-retro.gif gif_index.txt cache_version.txt README.md
        git commit -m "Update GIF $(date +%H:%M:%S)"
        git push